"""
audit_log.py
────────────
Phase 7F — Append-only audit trail for every trading event.

Rules:
  - NEVER UPDATE or DELETE rows — append only
  - Every signal, order, fill, rejection, mode change, kill switch is logged
  - Required for SEBI compliance when managing others' money
  - CSV export available for offline review

Events logged:
  SIGNAL_GENERATED   — strategy produced a signal
  SIGNAL_REJECTED    — signal blocked (intelligence, risk, validity)
  ORDER_PLACED       — order sent to broker
  ORDER_FILLED       — order confirmed filled
  ORDER_FAILED       — broker rejected or timed out
  POSITION_OPENED    — position recorded in portfolio
  POSITION_CLOSED    — position exited (P&L recorded)
  STOP_HIT           — stop loss triggered
  TARGET_HIT         — target 1 or 2 triggered
  TRAILING_STOP      — trailing stop updated
  MODE_CHANGE        — AUTO ↔ MANUAL switch
  KILL_SWITCH        — kill switch activated or reset
  PAPER_TRADE        — paper trading fill (separate from live)
  BOT_START          — bot process started
  BOT_STOP           — bot process stopped
  TOKEN_REFRESH      — Fyers token refreshed
  INTELLIGENCE_VETO  — intelligence layer blocked a trade

Usage:
    from audit_log import audit_log

    audit_log.signal(signal, reason="APPROVED")
    audit_log.order(symbol, order_id, direction, qty, price, order_type)
    audit_log.fill(symbol, order_id, fill_price, fill_qty)
    audit_log.rejection(signal, reason)
    audit_log.mode_change(old_mode, new_mode)
    audit_log.kill_switch(activated=True, reason="Daily loss limit hit")
    audit_log.bot_event("BOT_START", {"mode": "AUTO", "capital": 500000})
    audit_log.export_csv(path="audit_export.csv")
"""

import csv
import json
import logging
import os
import sqlite3
import threading
from datetime import datetime, timezone
from typing import Optional

from config.settings import DB_PATH

logger = logging.getLogger(__name__)

AUDIT_DB_PATH = DB_PATH.replace("trades.db", "audit.db")

# ── Schema ────────────────────────────────────────────────────────
_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS audit_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp   TEXT    NOT NULL,           -- ISO 8601 UTC
    event_type  TEXT    NOT NULL,           -- see module docstring
    symbol      TEXT    DEFAULT '',
    direction   TEXT    DEFAULT '',         -- LONG / SHORT / ''
    qty         INTEGER DEFAULT 0,
    price       REAL    DEFAULT 0,
    order_id    TEXT    DEFAULT '',
    strategy    TEXT    DEFAULT '',
    reason      TEXT    DEFAULT '',         -- human-readable context
    details     TEXT    DEFAULT '{}',       -- JSON blob for extra fields
    paper       INTEGER DEFAULT 0           -- 1 if paper trade
)
"""


class AuditLog:
    """
    Thread-safe, append-only audit log for all trading events.
    Writes to a separate SQLite database from trades.db.
    """

    def __init__(self):
        self._lock = threading.Lock()
        self._init_db()

    # ─────────────────────────────────────────────────────────────
    # PUBLIC LOGGING METHODS
    # ─────────────────────────────────────────────────────────────

    def signal(self, signal, reason: str = "") -> None:
        """Log a signal generated by a strategy."""
        self._write(
            event_type = "SIGNAL_GENERATED",
            symbol     = signal.symbol,
            direction  = signal.direction.value if hasattr(signal.direction, "value") else str(signal.direction),
            strategy   = signal.strategy,
            price      = signal.entry,
            reason     = reason or signal.reason[:200],
            details    = {
                "stop_loss":   signal.stop_loss,
                "target_1":    signal.target_1,
                "confidence":  signal.confidence,
                "risk_reward": signal.risk_reward,
                "regime":      signal.regime,
                "signal_type": signal.signal_type.value if hasattr(signal.signal_type, "value") else "",
            },
        )

    def rejection(self, signal, reason: str, layer: str = "risk") -> None:
        """Log a signal that was blocked before execution."""
        event = "INTELLIGENCE_VETO" if layer == "intelligence" else "SIGNAL_REJECTED"
        self._write(
            event_type = event,
            symbol     = signal.symbol,
            direction  = signal.direction.value if hasattr(signal.direction, "value") else str(signal.direction),
            strategy   = signal.strategy,
            price      = signal.entry,
            reason     = reason[:500],
            details    = {"layer": layer, "confidence": signal.confidence},
        )

    def order(
        self,
        symbol:     str,
        order_id:   str,
        direction:  str,
        qty:        int,
        price:      float,
        order_type: str = "MARKET",
        strategy:   str = "",
        paper:      bool = False,
    ) -> None:
        """Log a broker order placement."""
        self._write(
            event_type = "PAPER_TRADE" if paper else "ORDER_PLACED",
            symbol     = symbol,
            direction  = direction,
            qty        = qty,
            price      = price,
            order_id   = order_id,
            strategy   = strategy,
            details    = {"order_type": order_type},
            paper      = paper,
        )

    def fill(
        self,
        symbol:     str,
        order_id:   str,
        fill_price: float,
        fill_qty:   int,
        paper:      bool = False,
    ) -> None:
        """Log a confirmed order fill."""
        self._write(
            event_type = "ORDER_FILLED",
            symbol     = symbol,
            qty        = fill_qty,
            price      = fill_price,
            order_id   = order_id,
            paper      = paper,
        )

    def order_failed(self, symbol: str, order_id: str, reason: str) -> None:
        """Log a broker rejection or timeout."""
        self._write(
            event_type = "ORDER_FAILED",
            symbol     = symbol,
            order_id   = order_id,
            reason     = reason[:200],
        )

    def position_opened(self, symbol: str, direction: str, qty: int,
                        fill_price: float, strategy: str, paper: bool = False) -> None:
        self._write(
            event_type = "POSITION_OPENED",
            symbol     = symbol,
            direction  = direction,
            qty        = qty,
            price      = fill_price,
            strategy   = strategy,
            paper      = paper,
        )

    def position_closed(
        self,
        symbol:    str,
        exit_price: float,
        pnl:       float,
        reason:    str,
        paper:     bool = False,
    ) -> None:
        event = {
            "STOP":      "STOP_HIT",
            "TARGET1":   "TARGET_HIT",
            "TARGET2":   "TARGET_HIT",
            "EOD_FORCED": "POSITION_CLOSED",
        }.get(reason.upper(), "POSITION_CLOSED")

        self._write(
            event_type = event,
            symbol     = symbol,
            price      = exit_price,
            reason     = reason,
            details    = {"pnl": round(pnl, 2)},
            paper      = paper,
        )

    def trailing_stop(self, symbol: str, old_sl: float, new_sl: float) -> None:
        self._write(
            event_type = "TRAILING_STOP",
            symbol     = symbol,
            reason     = f"SL moved {old_sl:.2f} → {new_sl:.2f}",
            details    = {"old_sl": old_sl, "new_sl": new_sl},
        )

    def mode_change(self, old_mode: str, new_mode: str) -> None:
        self._write(
            event_type = "MODE_CHANGE",
            reason     = f"{old_mode} → {new_mode}",
            details    = {"old": old_mode, "new": new_mode},
        )

    def kill_switch(self, activated: bool, reason: str = "") -> None:
        self._write(
            event_type = "KILL_SWITCH",
            reason     = reason[:500],
            details    = {"activated": activated},
        )

    def bot_event(self, event_type: str, details: Optional[dict] = None) -> None:
        """Log BOT_START, BOT_STOP, TOKEN_REFRESH etc."""
        self._write(
            event_type = event_type,
            details    = details or {},
        )

    # ─────────────────────────────────────────────────────────────
    # EXPORT
    # ─────────────────────────────────────────────────────────────

    def export_csv(self, path: str = "db/audit_export.csv") -> str:
        """Export full audit log to CSV. Returns path."""
        try:
            with sqlite3.connect(AUDIT_DB_PATH) as conn:
                conn.row_factory = sqlite3.Row
                rows = conn.execute(
                    "SELECT * FROM audit_log ORDER BY id"
                ).fetchall()

            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                if rows:
                    writer.writerow(rows[0].keys())
                    for row in rows:
                        writer.writerow(list(row))

            logger.info(f"[AuditLog] Exported {len(rows)} rows → {path}")
            return path
        except Exception as e:
            logger.error(f"[AuditLog] Export failed: {e}")
            return ""

    def get_recent(self, limit: int = 50, event_type: Optional[str] = None) -> list[dict]:
        """Fetch recent audit entries for dashboard display."""
        try:
            with sqlite3.connect(AUDIT_DB_PATH) as conn:
                conn.row_factory = sqlite3.Row
                if event_type:
                    rows = conn.execute(
                        "SELECT * FROM audit_log WHERE event_type=? ORDER BY id DESC LIMIT ?",
                        (event_type, limit)
                    ).fetchall()
                else:
                    rows = conn.execute(
                        "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?",
                        (limit,)
                    ).fetchall()
            return [dict(r) for r in rows]
        except Exception as e:
            logger.error(f"[AuditLog] get_recent failed: {e}")
            return []

    # ─────────────────────────────────────────────────────────────
    # INTERNAL
    # ─────────────────────────────────────────────────────────────

    def _write(
        self,
        event_type: str,
        symbol:     str   = "",
        direction:  str   = "",
        qty:        int   = 0,
        price:      float = 0.0,
        order_id:   str   = "",
        strategy:   str   = "",
        reason:     str   = "",
        details:    dict  = None,
        paper:      bool  = False,
    ) -> None:
        """Core append-only write. Never updates existing rows."""
        with self._lock:
            try:
                details_json = json.dumps(details or {}, default=str)
                with sqlite3.connect(AUDIT_DB_PATH) as conn:
                    conn.execute(
                        """
                        INSERT INTO audit_log
                        (timestamp, event_type, symbol, direction, qty, price,
                         order_id, strategy, reason, details, paper)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            datetime.now(tz=timezone.utc).isoformat(),
                            event_type, symbol, direction, qty, price,
                            order_id, strategy, reason, details_json,
                            1 if paper else 0,
                        )
                    )
            except Exception as e:
                # Audit log failure must never crash the bot
                logger.error(f"[AuditLog] Write failed ({event_type} {symbol}): {e}")

    def _init_db(self) -> None:
        """Create audit table if it doesn't exist."""
        try:
            os.makedirs(os.path.dirname(AUDIT_DB_PATH), exist_ok=True)
            with sqlite3.connect(AUDIT_DB_PATH) as conn:
                conn.execute(_CREATE_TABLE)
            logger.info(f"[AuditLog] DB ready: {AUDIT_DB_PATH}")
        except Exception as e:
            logger.error(f"[AuditLog] DB init failed: {e}")


# ── Module-level singleton ────────────────────────────────────────
audit_log = AuditLog()
